name: Gosec scan via GHA

on:
    push:
     branches:
      - main
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Gosec scan
        uses: cloudbees-io-gha/gosec-scan-publish@update-image
        with:
          cloudbees-url: https://api.saas-qa.beescloud.com
          
          
         
